uploads = []
outputs = []

[[generated]]
id = "P8GWbuT3kNCPI9HD5Lsfw"
uri = "file://artifacts/portfolio/src/assets/project-1.png"
type = "image"
title = "Power BI Ticketing Dashboard abstract"

[[generated]]
id = "DlnkZWzNWALs-_dNivRFa"
uri = "file://artifacts/portfolio/src/assets/project-2.png"
type = "image"
title = "Cloud ETL Pipeline abstract"

[[generated]]
id = "iVMXx7M8MN2iHUDAGMgv8"
uri = "file://artifacts/portfolio/src/assets/project-3.png"
type = "image"
title = "Machine Learning Gesture abstract"
